# fly.toml app configuration file generated for schedgen-pdf-worker on 2025-12-06T00:02:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'schedgen-pdf-worker'
primary_region = 'jnb'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = '5001'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 5001
  auto_stop_machines = 'stop'
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
